name: build-and-release-dagster-vertexai

on:
  push:
    tags:
      - 'dagster_vertexai-*.*.*'

jobs:
  build-and-release-dagster-vertexai:
    uses: ./.github/workflows/template-release.yml
    with:
      library_name: dagster-vertexai
      working_directory: ./libraries/dagster-vertexai
    secrets: inherit
