name: build-and-release-dagster-apprise

on:
  push:
    tags:
      - 'dagster_apprise-*.*.*'

jobs:
  build-and-release-dagster-apprise:
    uses: ./.github/workflows/template-release.yml
    with:
      library_name: dagster-apprise
      working_directory: ./libraries/dagster-apprise
    secrets: inherit
